language: node_js
node_js:
  - '10'
cache:
  npm: true
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run build
  - mkdir deploy
  - cp -r index.html deploy/index.html
  - mv ./dist deploy/dist
  - mv ./static deploy/static
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  local_dir: deploy/
  fqdn: verifique.me
  on:
    branch: master

